version: '3.8'

networks:
  fune-network:
    driver: bridge

services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fune_db
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - fune-network
    container_name: fune-db

  app:
    image: hakim060701/fune-be:v1.5
    container_name: fune-be
    restart: unless-stopped
    volumes:
      - .:/var/www
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: fune_db
      DB_USERNAME: root
      DB_PASSWORD: 12345678
    depends_on:
      - db
    networks:
      - fune-network

  nginx:
    container_name: nginx-service
    restart: unless-stopped
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - 9001:80
    networks:
      - fune-network
    depends_on:
      - app
